apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: springboot-maven
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: springboot-maven
  namespace: my-apps
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
    - name: BP_SPRING_CLOUD_BINDINGS_DISABLED
      value: "true"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/language: java
      apps.tanzu.vmware.com/pipeline: test
  - name: testing_pipeline_params
    value:
      source-sub-path: .
  - name: gitops_ssh_secret
    value: git-secret
  source:
    git:
      ref:
        branch: main
      url: https://github.com/robertocolella/springboot-maven
